/**
 * Build src/ui/cardArt.ts — a map of card defId → require(image) — by scanning
 * the (gitignored) assets/cards/ folder and matching filenames to CARD_DEFS by
 * normalized card name. Run: npm run gen:art
 *
 * Card folders: Neutral, NRealms, Nilfgaard, Monster, Scoiatael (one PNG per
 * card, named "<Faction>-NNN-DescriptiveName.png"; duplicates for multi-copy
 * cards share one def, first file wins). leaders/<base><1..N>.png map to the
 * Nth leader of that faction in data order. Prints a coverage report; any
 * unmatched card simply keeps the programmatic frame.
 *
 * The output (src/ui/cardArt.ts) is committed alongside assets/cards/ so EAS
 * cloud builds ship the art — keep this repo private if it ever gets a remote.
 */

import { readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { CARD_DEFS } from '../src/engine/data/cards.ts';
import type { Faction } from '../src/engine/types.ts';

const root = join(import.meta.dirname ?? '.', '..');
const cardsDir = join(root, 'assets', 'cards');

const FOLDER_FACTION: Record<string, Faction> = {
  Neutral: 'neutral',
  NRealms: 'northern_realms',
  Nilfgaard: 'nilfgaard',
  Monster: 'monsters',
  Scoiatael: 'scoiatael',
};
const LEADER_BASE: Record<string, Faction> = {
  foltest: 'northern_realms',
  emhyr: 'nilfgaard',
  eredin: 'monsters',
  francesca: 'scoiatael',
};

const IMAGE_RE = /\.(png|jpe?g|webp)$/i;
const stem = (file: string): string => file.replace(IMAGE_RE, '');

/** Hand-mapped stragglers whose filename spelling won't auto-match the def. */
const OVERRIDES: Record<string, string> = {
  // defId: filename stem (no extension)
  st_isengrim: 'Scoiatael-003-IsengrimFaolitarna',
  st_ciaran: 'Scoiatael-026-CiaranAepEasnillien',
};

const norm = (s: string): string =>
  s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]/g, '');

const requirePath = (absFile: string): string => {
  let p = relative(join(root, 'src', 'ui'), absFile).split('\\').join('/');
  if (!p.startsWith('.')) {
    p = `./${p}`;
  }
  return p;
};

const map: Record<string, string> = {};
const unmatchedFiles: string[] = [];

function readDir(dir: string): string[] {
  try {
    return readdirSync(dir).filter((f) => IMAGE_RE.test(f));
  } catch {
    return [];
  }
}

// Units & specials, matched by normalized name within each faction folder.
for (const [folder, faction] of Object.entries(FOLDER_FACTION)) {
  const dir = join(cardsDir, folder);
  const defs = CARD_DEFS.filter((d) => d.faction === faction && d.type !== 'leader');
  for (const file of readDir(dir)) {
    const override = Object.entries(OVERRIDES).find(([, s]) => s === stem(file));
    if (override) {
      if (!map[override[0]]) {
        map[override[0]] = requirePath(join(dir, file));
      }
      continue;
    }
    const key = norm(stem(file).split('-').slice(2).join('-'));
    const def =
      defs.find((d) => norm(d.name) === key) ??
      defs.find((d) => norm(d.name).startsWith(key) || key.startsWith(norm(d.name)));
    if (def) {
      if (!map[def.id]) {
        map[def.id] = requirePath(join(dir, file));
      }
    } else {
      unmatchedFiles.push(`${folder}/${file}`);
    }
  }
}

// Leaders: <base><index>.png → the Nth leader of that faction in data order.
const leaderDir = join(cardsDir, 'leaders');
const leaderFiles = readDir(leaderDir);
for (const [base, faction] of Object.entries(LEADER_BASE)) {
  const leaders = CARD_DEFS.filter((d) => d.faction === faction && d.type === 'leader');
  leaders.forEach((leader, i) => {
    const file = leaderFiles.find((f) => norm(stem(f)) === `${base}${i + 1}`);
    if (file && !map[leader.id]) {
      map[leader.id] = requirePath(join(leaderDir, file));
    }
  });
}

// Report.
const deckable = CARD_DEFS.filter((d) => (d.maxCopiesPerDeck ?? 1) > 0);
const missing = deckable.filter((d) => !map[d.id]);
console.log(`Matched art for ${Object.keys(map).length} / ${deckable.length} deckable cards.`);
if (unmatchedFiles.length > 0) {
  console.log(`Unmatched files (${unmatchedFiles.length}): ${unmatchedFiles.join(', ')}`);
}
console.log(`No art (programmatic fallback): ${missing.map((d) => d.id).join(', ') || 'none'}`);

const entries = Object.entries(map)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, p]) => `  '${id}': require('${p}'),`)
  .join('\n');

writeFileSync(
  join(root, 'src', 'ui', 'cardArt.ts'),
  `/* GENERATED by npm run gen:art — defId -> bundled card image.\n` +
    ` * Unmatched cards use the programmatic CardView frame. */\n` +
    `export const CARD_ART: Record<string, number> = {\n${entries}\n};\n`,
);
console.log('Wrote src/ui/cardArt.ts');
